--- 
document:
  name: Schede informative basi di dati di interesse nazionale
  description: |
    Questo documento rappresenta il risultato dell’azione “Pubblicazione
    elenco basi di dati di interesse nazionale” definita nell’ambito delle
    Basi di dati di interesse nazionale del Piano Triennale per l’Informatica
    nella PA (2017-2019).
  tags:
    - pianotriennale
